[package]
name = "scatter-gather"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version= "*", features = ["full"] }
tungstenite = { version= "*", features= ["rustls-tls"]}
tokio-tungstenite = { version= "*", features= ["rustls-tls"] }
url = "*"
redis = { version = "0.19.0", features = ["tokio-comp", "tokio-native-tls-comp"] }
serde_json = "1.0"
scatter-gather-core = { path = "core" }

[workspace]
members = [
    "core",
    "middleware/scatter-gather-grpc",
    "middleware/scatter-gather-websockets",
    "middleware/scatter-gather-redis",
]