[package]
name = "scatter-gather-core"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version= "*", features = ["full"] }
futures = "0.3"
futures-channel = "0.3"